//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeJesus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksContent
    {
        public int BooksContentId { get; set; }
        public string Book { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ContributorId { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
