//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeJesus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributor
    {
        public Contributor()
        {
            this.BooksContents = new HashSet<BooksContent>();
            this.PrayerRequests = new HashSet<PrayerRequest>();
            this.PrayersContents = new HashSet<PrayersContent>();
        }
    
        public int ContributorId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LastContributionDate { get; set; }
    
        public virtual ICollection<BooksContent> BooksContents { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<PrayerRequest> PrayerRequests { get; set; }
        public virtual ICollection<PrayersContent> PrayersContents { get; set; }
    }
}
