//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeJesus.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LikeJesusEntities : DbContext
    {
        public LikeJesusEntities()
            : base("name=LikeJesusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BooksContent> BooksContents { get; set; }
        public DbSet<Contributor> Contributors { get; set; }
        public DbSet<PrayerRequest> PrayerRequests { get; set; }
        public DbSet<PrayersContent> PrayersContents { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
