//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeJesus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.BooksContents = new HashSet<BooksContent>();
            this.Contributors = new HashSet<Contributor>();
            this.PrayerRequests = new HashSet<PrayerRequest>();
            this.PrayersContents = new HashSet<PrayersContent>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Sex { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual ICollection<BooksContent> BooksContents { get; set; }
        public virtual ICollection<Contributor> Contributors { get; set; }
        public virtual ICollection<PrayerRequest> PrayerRequests { get; set; }
        public virtual ICollection<PrayersContent> PrayersContents { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
